legacy_traits_power_scores = {
    "blood plague survivor": 20,
    "auto detailer": 17,
    "drinks cold medicine": 17,
    "fastidious": 17,
    "incredible immune system": 17,
    "neat": 17,
    "vegan": 17,
    "carries hand sanitizer": 15,
    "cleaned offices": 15,
    "convention volunteer": 15,
    "forensic scientist": 15,
    "from a big family": 15,
    "germophobe": 15,
    "good habits": 15,
    "hand model": 15,
    "hates shiny food": 15,
    "homemaker": 15,
    "hotelier": 15,
    "house had black mold": 15,
    "lived in squalor": 2,
    "never been sick": 15,
    "prison tattoo artist": 15,
    "sewage system operator": 15,
    "tattoo artist": 15,
    "window cleaner": 15,
    "exuberant": 13,
    "baseball fan": 12,
    "basketball fan": 10,
    "beatboxer": 12,
    "blacksmith": 12,
    "football fan": 10,
    "got into bar fights": 12,
    "jogger": 12,
    "loves to sing": 12,
    "opera singer": 12,
    "paintballer": 12,
    "pro football player": 12,
    "professional singer": 12,
    "sang in a band": 12,
    "saxophonist": 12,
    "skeet shooter": 12,
    "watched sports": 10,
    "amateur hypnotist": 10,
    "army brat": 10,
    "band geek": 10,
    "bouncer": 10,
    "broad-shouldered": 10,
    "can take a punch": 10,
    "cat burglar": 10,
    "crazy metabolism": 10,
    "determined": 10,
    "early riser": 10,
    "electrician": 10,
    "energetic": 10,
    "football star": 10,
    "foster parent": 10,
    "from a fishing town": 10,
    "from a rural area": 10,
    "from the great lakes": 10,
    "generator technician": 10,
    "golfer": 10,
    "hard as nails": 10,
    "hardy": 10,
    "has rough hands": 10,
    "heavy hitter": 10,
    "high lung capacity": 10,
    "high metabolism": 10,
    "high pain threshold": 10,
    "high school athlete": 10,
    "high school mascot": 10,
    "indefatigable": 10,
    "internet troll": 10,
    "into roller derby": 10,
    "into ultimate frisbee": 10,
    "just keeps going": 10,
    "left for dead": 10,
    "licensed birth coach": 10,
    "lived at a high altitude": 10,
    "lived in the desert": 10,
    "materials engineer": 0,
    "meter reader": 10,
    "military washout": 10,
    "miner": 10,
    "moved around at night": 10,
    "night watch": 10,
    "no filter": 10,
    "nuclear scientist": 10,
    "paparazzi": 10,
    "piano mover": 10,
    "played basketball": 10,
    "played rugby": 10,
    "played soccer": 10,
    "played softball": 0,
    "played sports": 10,
    "played tetherball": 10,
    "preschool teacher": 10,
    "prison guard": 10,
    "punched nazis": 10,
    "resilient": 10,
    "school bully": 10,
    "sleep researcher": 10,
    "sleeps with dakimakura": 10,
    "snarky": 10,
    "spelunker": 10,
    "sports gambler": 10,
    "stargazer": 10,
    "stays fit": 10,
    "strong": 10,
    "strong back": 10,
    "takes power naps": 10,
    "tough": 10,
    "used to humidity": 10,
    "used to the cold": 10,
    "worked at power station": 10,
    "young": 10,
    "youth baseball coach": 10,
    "bagpiper": 8,
    "dolorous": 8,
    "sees blood and faints": 8,
    "sheltered": 8,
    "cancer survivor": 7,
    "former bodybuilder": 7,
    "loves to be scared": 7,
    "adrenaline junkie": 5,
    "awful fashion sense": 5,
    "base jumper": 5,
    "basket weaver": 5,
    "beekeeper": 5,
    "blew stuff up": 5,
    "bounty hunter": 0,
    "boxing coach": 5,
    "brave": 5,
    "cheerful": 5,
    "climber": 0,
    "combat engineer": 5,
    "competitive shooter": 5,
    "confident": 5,
    "cosplayer": 5,
    "crochet artist": 5,
    "cross-stitcher": 5,
    "dancer": 5,
    "daredevil": 5,
    "decathlete": 5,
    "endurance cyclist": 5,
    "english major": 5,
    "erratic": 5,
    "feckless": 5,
    "fights defensively": 5,
    "fitness boxer": 5,
    "fitness instructor": 5,
    "foolhardy": 5,
    "former goth": 5,
    "fought in the pits": 5,
    "fresh-faced": 5,
    "goofball": 5,
    "gym rat": 5,
    "had an electric fence": 5,
    "hang glider": 5,
    "hard to kill": 5,
    "has allergies": 5,
    "has seen it all": 5,
    "has severe allergies": 5,
    "having midlife crisis": 5,
    "hopeful": 5,
    "huge savings account": 5,
    "ice road trucker": 5,
    "immortal": 5,
    "inspired by courage": 5,
    "into weaving": 5,
    "island survivor": 5,
    "knife thrower": 5,
    "knitter": 5,
    "laughs easily": 5,
    "lived on the bayou": 5,
    "loves fireworks": 0,
    "made an indie game": 5,
    "martial arts teacher": 5,
    "military larper": 5,
    "mountain biker": 5,
    "nerve damage": 5,
    "never cries": 5,
    "nine lives": 5,
    "no belief in destiny": 5,
    "once ran for days": 5,
    "optimist": 5,
    "overcame fears": 5,
    "perpetual underdog": 5,
    "plane crash survivor": 5,
    "played zombie games": 5,
    "punches walls": 5,
    "pyromaniac": 5,
    "quilter": 5,
    "rebellious as a teen": 5,
    "renaissance fairgoer": 5,
    "rock climber": 5,
    "science geek": 0,
    "separated from unit": 5,
    "sold crafts online": 5,
    "theme park enthusiast": 5,
    "thrillseeker": 5,
    "took a lot of dares": 5,
    "took kickboxing": 5,
    "turned life around": 5,
    "unbreakable": 5,
    "unusually mature": 5,
    "urban climber": 5,
    "veteran gambler": 5,
    "was homeless": 5,
    "wingsuit flyer": 5,
    "wise": 5,
    "action choreographer": 3,
    "active duty military": 3,
    "air marshal": 3,
    "amateur acrobat": 3,
    "angsty": 3,
    "army grunt": 3,
    "army motor pool": 3,
    "astronomer": 3,
    "biathlete": 3,
    "blogger": 3,
    "bmx competitor": 3,
    "bold driver": 3,
    "bus driver": 3,
    "caravan driver": 3,
    "career coach": 3,
    "clever": 3,
    "code ninja": 3,
    "college fencer": 3,
    "college freshman": 3,
    "college professor": 3,
    "combat medic": 3,
    "decent shot": 3,
    "dependable friend": 3,
    "did trampoline stunts": 3,
    "dirty cop": 3,
    "drag racer": 3,
    "drove a crappy car": 3,
    "ethnobotanist": 3,
    "ethnomusicologist": 3,
    "fanfic writer": 3,
    "film director": 3,
    "former billionaire": 3,
    "former gang member": 3,
    "freelance consultant": 3,
    "freerunner": 3,
    "game designer": 3,
    "geologist": 3,
    "good arm": 3,
    "good listener": 3,
    "grognard": 3,
    "guidance counselor": 3,
    "habitual volunteer": 3,
    "had weapons training": 3,
    "hearse driver": 3,
    "highway patrol": 3,
    "idealist": 3,
    "idyllic childhood": 3,
    "indie app developer": 3,
    "juggler": 3,
    "k9 officer": 3,
    "kind eyes": 3,
    "lecturer": 3,
    "lichenologist": 3,
    "likes to fight": 3,
    "loved school": 3,
    "loves to drive": 3,
    "mall cop": 3,
    "mcp certified": 3,
    "mma fighter": 3,
    "motorcycle enthusiast": 3,
    "muni rider": 3,
    "navy veteran": 3,
    "neurotic": 3,
    "nimble": 3,
    "offroad biker": 3,
    "overachiever": 3,
    "pageant wagoneer": 2,
    "paralegal": 3,
    "patient": 3,
    "philosophy major": 3,
    "pinball wizard": 3,
    "police detective": 3,
    "police officer": 3,
    "police sergeant": 3,
    "professional hunter": 3,
    "quick on the draw": 3,
    "research assistant": 3,
    "respects authority": 3,
    "retired soldier": 3,
    "science editor": 3,
    "security guard": 3,
    "sheriff's deputy": 3,
    "sign twirler": 3,
    "skater": 3,
    "software engineer": 3,
    "special forces": 3,
    "state trooper": 3,
    "straight-a student": 3,
    "student mentor": 3,
    "swat breacher": 3,
    "swat officer": 3,
    "swat trainee": 3,
    "tech early adopter": 3,
    "took online courses": 3,
    "took self defense": 3,
    "tractor driver": 3,
    "trade school teacher": 3,
    "traffic cop": 3,
    "us marshal": 3,
    "used to be reckless": 3,
    "user experience designer": 3,
    "went to grad school": 3,
    "willowy": 3,
    "zine author": 3,
    "a little sadistic": 2,
    "action videographer": 2,
    "agriculture professor": 2,
    "all out of fucks": 2,
    "always paid for dinner": 2,
    "always wanted to camp": 2,
    "amateur comic": 2,
    "amateur painter": 2,
    "ammo hoarder": 2,
    "anarchist": 2,
    "architect": 2,
    "aspiring vigilante": 2,
    "astronomy professor": 2,
    "at home in a bar": 2,
    "attended trade school": 2,
    "audiophile": 2,
    "auto body technician": 2,
    "automechanic": 2,
    "automotive technician": 2,
    "avid game player": 2,
    "avid hunter": 2,
    "backpacker": 2,
    "bad back": -17,
    "baker": 2,
    "ballet dancer": 2,
    "ballroom dancer": 2,
    "bartender": 2,
    "basement dweller": 2,
    "beer lover": 2,
    "booze nerd": 2,
    "botanist": 2,
    "brush clearer": 2,
    "building a gyrocopter": 2,
    "building super": 2,
    "built battle robots": 2,
    "burned it all down": 2,
    "cabinetmaker": 2,
    "cake decorator": 2,
    "camp counselor": 2,
    "campfire cook": 2,
    "candlestick maker": 2,
    "car hobbyist": 2,
    "caravan mechanic": 2,
    "caring": 2,
    "carny": 2,
    "changed jobs a lot": 2,
    "chef": 2,
    "coffee connoisseur": 2,
    "comic book dealer": 2,
    "comic collector": 2,
    "compulsive gardener": 2,
    "confectioner": 2,
    "conspiracy theorist": 2,
    "construction manager": 2,
    "contractor": 2,
    "cult film junkie": 2,
    "customer service": 2,
    "d-i-y remodeler": 2,
    "deer hunter": 2,
    "dental hygienist": 2,
    "designated marksman": 2,
    "diesel mechanic": 2,
    "digital artist": 2,
    "does tons of squats": 2,
    "does yoga": 2,
    "dog person": 2,
    "drummer": 2,
    "encouraging": 0,
    "environmentalist": 0,
    "excellent game master": 2,
    "exiled": 2,
    "exotic dancer": 2,
    "extremely loyal": 2,
    "face painter": 2,
    "factory manager": 2,
    "farm manager": 2,
    "farmer": 2,
    "farmhand": 2,
    "film buff": 2,
    "film critic": 2,
    "filthy": 2,
    "firewatch officer": 2,
    "flatulent": 2,
    "florist": 2,
    "foam dart champion": 2,
    "food hoarder": 2,
    "food truck owner": 2,
    "foodie": 2,
    "foot pain": 2,
    "former aquarium security": 2,
    "former metalhead": 2,
    "former rock star": 2,
    "forum admin": 2,
    "funny": 2,
    "furniture adjuster": 2,
    "furniture restorer": 2,
    "gardener": 2,
    "gas hoarder": 2,
    "geocacher": 2,
    "gets rashes": 2,
    "ghost writer": 2,
    "glazier": 2,
    "glutton": 2,
    "got fired a lot": 2,
    "gracious": 2,
    "great cook": 2,
    "green thumb": 2,
    "grew tomatoes": 2,
    "grew up around cars": 2,
    "grew up on a farm": 2,
    "guitarist": 2,
    "gun spinner": 2,
    "had a flower garden": 2,
    "had a garage band": 2,
    "had a gorgeous backyard": 2,
    "had a son": 2,
    "had an absent father": 2,
    "had an herb garden": 2,
    "had lan parties": 2,
    "halitosis": 2,
    "handy": 2,
    "hardcore prepper": 2,
    "hated thanksgiving": 2,
    "hates trespassers": 2,
    "hemp enthusiast": 2,
    "hiker": 2,
    "hit the range": 2,
    "hoarder": 2,
    "holding out hope": 2,
    "holed up at a farm": 2,
    "homebrewer": 2,
    "hong kong cinema fan": 2,
    "human resources": 2,
    "hunting trips": 2,
    "hvac repair": 2,
    "hypochondriac": 2,
    "immature": 2,
    "interior designer": 2,
    "into cheesy movies": 2,
    "into gardening shows": 2,
    "into nostalgia": 2,
    "irresponsible": 2,
    "jeweler": 2,
    "judge": 2,
    "jury-rigger": 2,
    "kendo instructor": 2,
    "kept smartphone": 2,
    "landscape architect": 2,
    "larper": 2,
    "leads from behind": 2,
    "led a quiet life": 2,
    "left someone behind": 2,
    "lies about age": 0,
    "likes army fatigues": 2,
    "loved being single": 2,
    "loved camping": 2,
    "loved going to movies": 2,
    "loved scary movies": 2,
    "loved to dance": 2,
    "loves baking": 0,
    "loves cars": 2,
    "loves spicy food": 2,
    "loves the outdoors": 2,
    "machiavellian": 2,
    "machinist": 2,
    "made cosplay swords": 2,
    "made science videos": 2,
    "makes art from junk": 2,
    "marathon runner": 2,
    "mason": 2,
    "measures twice": 2,
    "medicine hoarder": 2,
    "meticulous": 2,
    "miniature collector": 2,
    "minored in chemistry": 2,
    "mixologist": 2,
    "moonshiner": 2,
    "never holds back": 2,
    "no belief in fairness": 2,
    "nostalgic": 2,
    "nurturing": 2,
    "oil and tire tech": 2,
    "operations manager": 2,
    "overcame anger issues": 2,
    "owned a nursery": 2,
    "painter": 2,
    "paronomasiac": 2,
    "part-time barista": 2,
    "pastry chef": 2,
    "patent collector": 2,
    "pc gamer": 2,
    "personal trainer": 2,
    "piano teacher": 2,
    "picky eater": 2,
    "picnicker": 2,
    "pit crew": 2,
    "played in a band": 2,
    "podcaster": 2,
    "political moderate": 2,
    "practical joker": 2,
    "prankster": 2,
    "prefers the sidelines": 2,
    "pro gamer": 2,
    "professional deejay": 2,
    "projectionist": 2,
    "property manager": 2,
    "propmaster": 2,
    "pulled all-nighters": 2,
    "puts family first": 2,
    "ran a secret grow op": 2,
    "rare book collector": 2,
    "reads books": 2,
    "ready for anything": 2,
    "reality tv star": 2,
    "recites tv shows": 2,
    "retro gamer": 2,
    "rifle collector": 2,
    "rodeo clown": 2,
    "salsa dancer": 2,
    "sarcastic": 2,
    "scout leader": 2,
    "sculptor": 2,
    "self defense teacher": 2,
    "self-destructive": 2,
    "separated": 2,
    "sewer dweller": 2,
    "shares everything": 2,
    "shop teacher": 2,
    "short as a kid": 2,
    "sings badly in public": 2,
    "sings in the shower": 2,
    "sleeps on the ground": 2,
    "slept in a tree": 2,
    "slouchy": 2,
    "slovenly": 2,
    "slump-shouldered": 2,
    "social butterfly": 2,
    "sociopathic vibe": 2,
    "solo scavenger": 2,
    "speedwalker": 2,
    "spent weekends antiquing": 2,
    "sportscar fanatic": 2,
    "spry": 2,
    "stained glass artist": 2,
    "stand-up comic": 2,
    "started flash mobs": 2,
    "sushi chef": 2,
    "sweats a lot": 2,
    "tabletop gamer": 2,
    "talks to plants": 2,
    "taught gymnastics": 2,
    "tech support": 2,
    "technically royalty": 2,
    "telemarketer": 2,
    "tells bad jokes": 0,
    "tells tall tales": 2,
    "theatre nerd": 2,
    "tinkerer": -8,
    "took a gap year": 2,
    "took crazy road trips": 2,
    "took decoy duty": 2,
    "trail guide": 2,
    "trilingual": 2,
    "typeface designer": 2,
    "unmotivated": 2,
    "used to hunt": 2,
    "useless": 2,
    "video game streamer": 2,
    "video rental clerk": 2,
    "voice actor": 2,
    "volunteer coordinator": 2,
    "wandering guitarist": 2,
    "war reenactor": 2,
    "was always sick": 2,
    "watched cooking shows": 2,
    "watched westerns": 2,
    "weekend warrior": 2,
    "weightlifter": 2,
    "went on camping trips": 2,
    "whittler": 2,
    "will drink anything": 2,
    "worked at an orchard": 2,
    "worked construction": 2,
    "worked on a farm": 2,
    "world war ii buff": 2,
    "wrote a viral tweet": 2,
    "accountant": 0,
    "action movie extra": 0,
    "admin assistant": 0,
    "advertiser": 0,
    "aeronautics engineer": 0,
    "afraid of everything": 0,
    "afraid of rats": 0,
    "air traffic control": 0,
    "aircraft mechanic": 0,
    "airsoft commando": 0,
    "always kept moving": 0,
    "always packed a lunch": 0,
    "always ready to move": 0,
    "always vigilant": 0,
    "amateur boxer": 0,
    "amateur pilot": 0,
    "ammo hobbyist": 0,
    "angler": 0,
    "animal control": 0,
    "animal lover": 0,
    "antiques buyer": 0,
    "anxious all the time": 0,
    "apprentice plumber": 0,
    "army engineer": 0,
    "army veteran": 0,
    "ascetic": 0,
    "assembly-line worker": 0,
    "assistant principal": 0,
    "attending physician": 0,
    "audio engineer": 0,
    "auditor": 0,
    "authoritarian": 0,
    "automated systems tech": 0,
    "autopsy technician": 0,
    "av technician": 0,
    "avionics technician": 0,
    "avoids first name": 0,
    "backwoods upbringing": 0,
    "bad leg": 0,
    "baggage handler": 0,
    "barber": 0,
    "barista": 0,
    "bbq master": 0,
    "bead crafter": 0,
    "beautician": 0,
    "behavior analyst": 0,
    "believes in people": 0,
    "bike courier": 0,
    "biochemist": 0,
    "biotech scientist": 0,
    "birdwatcher": 0,
    "blade collector": 0,
    "bleak outlook": 0,
    "bodyguard": 0,
    "breaking champion": 0,
    "bronto gas attendant": 0,
    "bronto gas cashier": 0,
    "built a pc": 0,
    "built a treehouse": 0,
    "built barricades": 0,
    "burglar": 0,
    "burly": 0,
    "busybody": 0,
    "butcher": 0,
    "cab driver": 0,
    "cable installer": 0,
    "cafeteria manager": 0,
    "camp physician": 0,
    "campaign manager": 0,
    "can sleep anywhere": 0,
    "canvasser": 0,
    "car thief": 0,
    "carpenter": 0,
    "cartographer": 0,
    "case modder": 0,
    "cashier": 0,
    "cat lover": 0,
    "cat person": 0,
    "cautious": 0,
    "ceo": 0,
    "cfo": 0,
    "chainsaw sculptor": 0,
    "charity worker": 0,
    "chemical engineer": 0,
    "chemist": 0,
    "chemistry professor": 0,
    "child care worker": 0,
    "child of celebrities": 0,
    "childhood gymnast": 0,
    "chiropractor": 0,
    "choral director": 0,
    "churrascaria server": 0,
    "city council member": 0,
    "community manager": 0,
    "competitive eater": 0,
    "competitive sniper": 0,
    "comptroller": 0,
    "compulsive upcycler": 0,
    "cookie shop employee": 0,
    "coupon cutter": 0,
    "covered wars": 0,
    "criminal leader": 0,
    "crossbow hunter": 0,
    "culinary specialist": 0,
    "custodian": 0,
    "dated online": 0,
    "day laborer": 0,
    "day trader": 0,
    "delivery driver": 0,
    "demolitionist": 0,
    "dense bone condition": 0,
    "dentist": 0,
    "did pool maintenance": 0,
    "dieter": 0,
    "disorganized": 0,
    "distrusts outsiders": 0,
    "diver": 0,
    "does heavy lifting": 0,
    "dog walker": 0,
    "dream therapist": 0,
    "drill sergeant": 0,
    "drug dealer": 0,
    "drug-resistant": 0,
    "eats like a bird": 0,
    "electrical engineer": 0,
    "empathetic": 0,
    "emt": 0,
    "engineering student": 0,
    "entourage member": 0,
    "entrepreneur": 0,
    "epidemiologist": 0,
    "erratic driver": 0,
    "euthanized animals": 0,
    "expert traveler": 0,
    "explosives engineer": 0,
    "exterminator": 0,
    "extremely competitive": 0,
    "factory worker": 0,
    "fast food worker": 0,
    "feels embarathy": 0,
    "fiery protester": 0,
    "fire marshal": 0,
    "firefighter": 0,
    "fish noodler": 0,
    "fished professionally": 0,
    "fixed refrigerators": 0,
    "fleet manager": 0,
    "flight attendant": 0,
    "flipped houses": 0,
    "food borrower": 0,
    "food critic": 0,
    "food sharer": 0,
    "forestry technician": 0,
    "forklift driver": 0,
    "former activist": 0,
    "former burglar": 0,
    "former homeowner": 0,
    "former inmate": 0,
    "former lieutenant": 0,
    "former lifeguard": 0,
    "former model": 0,
    "former pacifist": 0,
    "former raider": 0,
    "former shut-in": 0,
    "fortified home": 0,
    "frequent anxiety": 0,
    "friendly": 0,
    "from a military family": 0,
    "frontier con artist": 0,
    "frontier deejay": 0,
    "frontier prospector": 0,
    "frontier runner": 0,
    "frontier scout": 0,
    "frontier sniper": 0,
    "fry cook": 0,
    "fugitive": 0,
    "funeral home director": 0,
    "gas station attendant": 0,
    "gave to every panhandler": 0,
    "general practitioner": 0,
    "generous": 0,
    "geneticist": 0,
    "geo systems engineer": 0,
    "getaway driver": 0,
    "gets carsick": 0,
    "goes by last name": 0,
    "golf caddy": 0,
    "good posture": 0,
    "got beaten up": 0,
    "greedy": 0,
    "grew up poor": 0,
    "groundskeeper": 0,
    "guilt-motivated": 0,
    "gun dealer": 0,
    "gunsmith": 0,
    "gymnast": 0,
    "gynecologist": 0,
    "had a beloved aunt": 0,
    "had a chemistry set": 0,
    "had a close cousin": 0,
    "had a loud neighbor": 0,
    "had a paper route": 0,
    "had a retirement fund": 0,
    "had a scholarship": 0,
    "had a troubled youth": 0,
    "had alcohol issues": 0,
    "had older brothers": 0,
    "hall monitor": 0,
    "halo champion": 0,
    "ham radio operator": 0,
    "has a lead foot": 0,
    "has a routine": 0,
    "has nightmares": -8,
    "hated camping": 0,
    "hated the boss": 0,
    "hates to be alone": 0,
    "held the line": 0,
    "helpful to a fault": 0,
    "hero complex": 0,
    "hesitant": 0,
    "hibachi cook": 0,
    "high school teacher": 0,
    "highly responsible": 0,
    "hits first, hits hard": 0,
    "homebody": 0,
    "hopeless romantic": 0,
    "horse jockey": 0,
    "horse surgeon": 0,
    "hospice nurse": 0,
    "hospital admin": 0,
    "hostler": 0,
    "huge jerk": 0,
    "hydraulics technician": 0,
    "hyper-partisan": 0,
    "hyper-prepared": 0,
    "impostor syndrome": 0,
    "in recovery": 0,
    "in the peace corps": 0,
    "in witness protection": 0,
    "in-home caregiver": 0,
    "incompetent": 0,
    "installed sprinklers": 0,
    "insular": 0,
    "into boxing": 0,
    "into fly fishing": 0,
    "into model trains": 0,
    "it worker": 0,
    "janitor": 0,
    "junkyard worker": 0,
    "katana barber": 0,
    "keeps a steady pace": 0,
    "keeps hidden pouches": 0,
    "kept a vigil": 0,
    "knife fighter": 0,
    "lab technician": 0,
    "landscaper": 0,
    "lapsed catholic": 0,
    "lawyer": 0,
    "learned about lichen": 0,
    "learned better hygiene": 0,
    "learned chemistry": 0,
    "learned computing": 0,
    "learned craftsmanship": 0,
    "learned mechanics": 0,
    "learned medicine": 0,
    "learned scrum": 0,
    "learned sleep psychology": 0,
    "learned soundproofing": 0,
    "learned to cook": 0,
    "learned to drive": 0,
    "learned to fish": 0,
    "learned to garden": 0,
    "learned to recycle": 0,
    "learned to sew": 0,
    "learned to shop": 0,
    "learned utilities": 0,
    "librarian": 0,
    "likes fishing": 0,
    "likes to take things": 0,
    "line cook": 0,
    "lived among celebrities": 0,
    "lived by a code": 0,
    "lived by the sword": 0,
    "lived downtown": 0,
    "lived in a bunker": 0,
    "lived on a rooftop": 0,
    "lived on spoiled food": 0,
    "lived on the road": 0,
    "lived out of a car": 0,
    "lives on pasta": 0,
    "local computer expert": 0,
    "locksmith": 0,
    "loose cannon cop": 0,
    "looter": 0,
    "lost a brother": 0,
    "lost a sister": 0,
    "lost family": 0,
    "lost father": 0,
    "lost wife": 0,
    "loved fast food": 0,
    "loved riding bikes": 0,
    "loved to hunt": 0,
    "loves canning": 0,
    "loves jigsaw puzzles": 0,
    "loves to explore": 0,
    "loves to mentor": 0,
    "lumberjack": 0,
    "magician": 0,
    "magnanimous": 0,
    "mail carrier": 0,
    "majored in chemistry": 0,
    "massage therapist": 0,
    "masseuse": 0,
    "meal delivery driver": 0,
    "mechanical engineer": 0,
    "medical researcher": 0,
    "meditates": 0,
    "meek": 0,
    "mentally trained": 0,
    "messy": 0,
    "microbiologist": 0,
    "middle manager": 0,
    "migrant worker": 0,
    "military contractor": 0,
    "military police": 0,
    "militia member": 0,
    "mobile developer": 0,
    "model hobbyist": 0,
    "motivational speaker": 0,
    "mountain climber": 0,
    "mud runner": 0,
    "mule driver": 0,
    "mycologist": 0,
    "mystery shopper": 0,
    "national guard": 0,
    "naturopath": 0,
    "needs alone time": 0,
    "needs quiet time": 0,
    "neighborhood watch": 0,
    "never fell in love": 0,
    "never used turn signals": 0,
    "news camera operator": 0,
    "nihilist": 0,
    "noisy": 0,
    "nomadic sleeper": 0,
    "nuclear engineer": 0,
    "nudist": 0,
    "nurse": 0,
    "nutritionist": 0,
    "observant": 0,
    "occasional hunter": 0,
    "occasionally narcoleptic": 0,
    "old veteran": 0,
    "once ate a gorilla": 0,
    "oncologist": 0,
    "operating engineer": 0,
    "orderly": 0,
    "organized": 0,
    "overplanner": 0,
    "pack rat": 0,
    "park ranger": 0,
    "partner in a law firm": 0,
    "passive aggressive": 0,
    "peacemaker": 0,
    "pedantic": 0,
    "pediatrician": 0,
    "pet rock artist": 0,
    "petroleum engineer": 0,
    "pharmacist": 0,
    "pharmacy technician": 0,
    "philanthropist": 0,
    "photographer": 0,
    "physically trained": 0,
    "pilot": 0,
    "plans ahead": 0,
    "plastic surgeon": 0,
    "played car games": 0,
    "plumber": 0,
    "police negotiator": 0,
    "political operative": 0,
    "poor bedside manner": 0,
    "poor typist": 0,
    "power engineer": 0,
    "powerline technician": 0,
    "practices ikebana": 0,
    "precise": 0,
    "private investigator": 0,
    "prize-winning chili": 0,
    "pro poker player": 0,
    "psychiatrist": 0,
    "public relations manager": 0,
    "pump tester": 0,
    "purse snatcher": 0,
    "pyrotechnician": 0,
    "quartermaster officer": 0,
    "quick study": 0,
    "rabble rouser": 0,
    "railroad engineer": 0,
    "raised by single mom": 0,
    "ran a bed & breakfast": 0,
    "ran a garden department": 0,
    "ran a medical office": 0,
    "ran the neighborhood": 0,
    "ranch hand": 0,
    "rc pilot": 0,
    "ready for action": 0,
    "real estate agent": 0,
    "reality tv failure": 0,
    "receptionist": 0,
    "reckless": -5,
    "rescued a puppy": 0,
    "rescues spiders": 0,
    "research engineer": 0,
    "reservist": 0,
    "restaurant manager": 0,
    "riding instructor": 0,
    "roadkill cook": 0,
    "rocket scientist": 0,
    "rural veterinarian": 0,
    "ruthless": 0,
    "safety engineer": 0,
    "sales associate": 0,
    "sales engineer": 0,
    "sanitation engineer": 0,
    "sawbones": 0,
    "science teacher": 0,
    "scout": 0,
    "scrapyard worker": 0,
    "security obsessed": 0,
    "self-conscious": 0,
    "self-effacing": 0,
    "self-promoter": 0,
    "sewer worker": 0,
    "shakespearean actor": 0,
    "sharp eyes": 0,
    "shoddy workmanship": 0,
    "shopped on tv": 0,
    "should not be crossed": 0,
    "shrewd": 0,
    "shy": 0,
    "sign painter": 0,
    "single parent": 0,
    "sister in the military": 0,
    "slaughterhouse worker": 0,
    "sleep technician": 0,
    "slightly stocky": 0,
    "small animal vet": 0,
    "smooth talker": 0,
    "smuggler": 0,
    "sniper": 0,
    "snowboarder": 0,
    "social worker": 0,
    "soft-hearted": 0,
    "sold cellular phones": 0,
    "sold electronics": 0,
    "sold fertilizer": 0,
    "sold supplements": 0,
    "someone's relative": 0,
    "sore neck": 0,
    "soup kitchen volunteer": 0,
    "speech therapist": 0,
    "spotter": 0,
    "stagehand": 0,
    "stamp collector": 0,
    "state senator": 0,
    "steady": 0,
    "stockroom worker": 0,
    "stored tons of food": 0,
    "street performer": 0,
    "stress eater": 0,
    "strict expectations": 0,
    "stubborn": 0,
    "stunt person": 0,
    "stylist": 0,
    "surgeon": 0,
    "surgical assistant": 0,
    "survivalist": 0,
    "survived indoors": 0,
    "survived on a train": 0,
    "survivor's guilt": 0,
    "talented athlete": 0,
    "talk radio host": 0,
    "talks loudly": 0,
    "tapped a water tower": 0,
    "taught elementary school": 0,
    "taxidermist": 0,
    "tech director": 0,
    "test engineer": 0,
    "the muscle": 0,
    "toll booth operator": 0,
    "too many textbooks": 0,
    "total lightweight": 0,
    "tour guide": 0,
    "tourist": 0,
    "track star": 0,
    "trained at fighting": 0,
    "trained at shooting": 0,
    "trained in cpr": 0,
    "training electrician": 0,
    "translator": 0,
    "trash collector": 0,
    "traveled the world": 0,
    "tree trimmer": 0,
    "trucker": 0,
    "trucker for westen": 0,
    "trusts no one": 0,
    "tsa agent": 0,
    "turned a corner": 0,
    "uncomfortable at parties": 0,
    "undertaker": 0,
    "unnervingly quiet": 0,
    "urban farmer": 0,
    "urologist": 0,
    "used to be vain": 0,
    "used to hate guns": 0,
    "used to hide money": 0,
    "used to paint": 0,
    "utilities worker": 0,
    "vacationed in spain": 0,
    "vain": 0,
    "valedictorian": 0,
    "vcr repair": 0,
    "very trusting": 0,
    "veterinarian": 0,
    "veterinary pathologist": 0,
    "video game producer": 0,
    "visited yard sales": 0,
    "vlogger": 0,
    "volunteer firefighter": 0,
    "voyeur": 0,
    "waited them out": 0,
    "waiter": 0,
    "wallflower": 0,
    "warehouse manager": 0,
    "warehouse stocker": 0,
    "was in rotc": 0,
    "was unemployed": 0,
    "waste disposal engineer": 0,
    "waste sorter": 0,
    "web developer": 0,
    "weird nickname": 0,
    "weirdo": 0,
    "well-built": 0,
    "went to night school": 0,
    "whistleblower": 0,
    "will eat anything": 0,
    "woodcutter": 0,
    "workaholic": 0,
    "worked at a chop shop": 0,
    "worked at an office": 0,
    "worked at tartan mart": 0,
    "yoga instructor": 0,
    "youth counselor": 0,
    "zombie hunter": 0,
    "zoologist": 0,
    "belligerent": -2,
    "braggart": -2,
    "can't sleep alone": -2,
    "complainer": -2,
    "frustrated": -2,
    "fussy": -2,
    "has an old work injury": -2,
    "has traumatic flashbacks": -2,
    "hates horror movies": -2,
    "in mourning": -2,
    "irritable": -2,
    "kleptomaniac": -2,
    "lacks boundaries": -2,
    "longsuffering martyr": -2,
    "nosy": -2,
    "panicky": -2,
    "pessimist": -2,
    "surly": -2,
    "trust fund kid": -2,
    "burned house down": -5,
    "gets migraines": -5,
    "has a pain disorder": -5,
    "has chronic pain": -5,
    "has fibromyalgia": -5,
    "hesitates in combat": -5,
    "soft": -5,
    "back pain": -7,
    "brittle": -7,
    "digestive problems": -7,
    "doomed": -7,
    "fears needles": -7,
    "food allergies": -7,
    "overconfident": -7,
    "pathetic": -7,
    "self-hating": -7,
    "a little forgetful": -8,
    "arthritis": -8,
    "bad shoulder": -8,
    "both knees replaced": -8,
    "cigar enthusiast": -8,
    "couch potato": -8,
    "easily bored": -8,
    "had knee replaced": -8,
    "has cataracts": -8,
    "hates exercise": -8,
    "heart problems": -8,
    "human potato": -8,
    "insomniac": -8,
    "joint problems": -8,
    "lazy": -8,
    "night terrors": -8,
    "serial plant murderer": -8,
    "sloth-like metabolism": -8,
    "stoner": -8,
    "tires quickly": -8,
    "quick to despair": -9,
    "absent-minded": -10,
    "always cold": -10,
    "bad carpenter": -10,
    "bad shot": -10,
    "built the worst deck": -10,
    "closed-minded": -10,
    "clumsy": -10,
    "computer \"expert": -10,
    "easily distracted": -10,
    "flincher": -10,
    "flinches at noises": -10,
    "food torturer": -10,
    "forgetful": -10,
    "grew up in suburbia": -10,
    "gullible": -10,
    "has astigmatism": -10,
    "has shaky hands": -10,
    "homeopath": -10,
    "hothead": -10,
    "inattentive cook": -10,
    "itchy trigger finger": -10,
    "kind of an idiot": -10,
    "lost security blanket": -10,
    "low metabolism": -10,
    "lurker": -10,
    "medicine merchant": -10,
    "nearsighted": -10,
    "never exercised": -10,
    "no common sense": -10,
    "overworked": -10,
    "panicky fighter": -10,
    "risk averse": -10,
    "scammed an employer": -10,
    "self-sabotaging": -10,
    "shady mechanic": -10,
    "skittish": -10,
    "slumming mechanic": -10,
    "snores": -10,
    "sold used cars": -10,
    "unathletic": -10,
    "unobservant": -10,
    "weak stomach": -10,
    "weak swing": -10,
    "worst fighter ever": -10,
    "lung cancer survivor": -13,
    "one lung": -15,
    "low pain treshold": -17,
    "asthma": -18,
    "decrepit": -18,
    "short of breath": -18,
    "old and tired": -20,
    "relied on an oxygen tank": -20,
    "run-down": -20,
    "smoker": -20
  }