play_style_configs = {
    "strategist": {
        "description": "Default: +Infection, +Stamina, +Health, +Training, +Morale, -Standing.",
        "infection": 1.5,
        "stamina": 1.5,
        "health": 1.2,
        "training": 1.2,
        "morale": 1.2,
        "default": 0.5,
        "standing_rewards": -1,
        "negative": -2,
        "positive": 0,
    },
    "beginner": {
        "description": "Easy: +Health, +Morale, +Training, +Stamina.",
        "health": 1.5,
        "morale": 1.2,
        "training": 1.2,
        "stamina": 1.2,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "mechanic": {
        "description": "Machines: +Vehicle, +Fuel, +Parts, +Labor, +Materials.",
        "vehicle": 2,
        "fuel": 1.5,
        "parts": 1.5,
        "labor": 1.2,
        "materials": 1.2,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "shadow": {
        "description": "Stealth: +Stealth, +Stamina, +Melee, +Infection, +Detection.",
        "stealth": 3,
        "stamina": 1.5,
        "melee": 1.5,
        "infection": 1,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "resourceful": {
        "description": "Resources: +Carry, +Food, +Meds, +Materials, +Parts, +Ammo, +Fuel.",
        "carrying_capacity": 3,
        "food": 1.5,
        "medicine": 1.5,
        "materials": 5,
        "parts": 3,
        "ammo": 1.5,
        "fuel": 1.5,
        "default": 0.1,
        "negative": 0,
        "positive": 0,
    },
    "prodigy": {
        "description": "Quick learner: +Skills, +Training, +Morale.",
        "training": 2,
        "morale": 1.5,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "farmer": {
        "description": "Support: +Food, +Meds, +Labor.",
        "labor": 1.5,
        "food": 1.5,
        "medicine": 1.5,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "diplomat": {
        "description": "Allies: +Standing, +Radio, +Influence, +Morale.",
        "standing_rewards": 1.5,
        "radio_usage": 1.2,
        "influence": 1.2,
        "morale": 1.2,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "berserker": {
        "description": "Fury: +Health, +Stamina, +Melee, +Infection, -Morale.",
        "health": 1.5,
        "stamina": 1.2,
        "melee": 1.2,
        "infection": 1.2,
        "morale": -1.5,
        "default": 0.5,
        "negative": 0,
        "positive": 0,        
    },
    "talbot": {
        "description": "Chaos: +Health, +Guns, +Fuel, +Stamina, +Ammo.",
        "health": 1.5,
        "guns": 1.5,
        "fuel": 1.2,
        "stamina": 1.2,
        "ammo": 1.0,
        "default": 0.5,
        "negative": 0,
        "positive": 0,
    },
    "masochist": {
        "description": "Pain: +Negatives, -Positives.",
        "default": 0,
        "negative": 1,
        "positive": -1,
    },
    "minmaxer": {
        "description": "Balance: Equal pros/cons.",
        "default": 0
    },
    "legacy": {
        "description": "Original mod version.",
        "default": 1
    },
}